Repository apache/nifi, pull requests merged in 2024-10, with the labels that each got.

#9330 [NIFI-13778] markdown syntax highlighting and h1-h5, tables, ul, and ol
  nifi-frontend/src/main/frontend/apps/nifi/project.json
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/documentation/ui/common/additional-details/additional-details.component.html
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/header/flow-status/flow-status.component.html
  nifi-frontend/src/main/frontend/apps/nifi/src/styles.scss
  nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_app.scss
  nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_codemirror-theme.scss
  nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_prism-theme.scss
  nifi-frontend/src/main/frontend/package-lock.json
  nifi-frontend/src/main/frontend/package.json
Labels: hacktoberfest-accepted, new ui

#9335 NIFI-13822: Ensuring the parameter value is always included when crea…
  nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/edit-parameter-dialog/edit-parameter-dialog.component.ts
Labels: hacktoberfest-accepted, new ui

#9329 [NIFI-13756] clear banner error afterClosed() of EditParameterContext…
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/parameter-contexts/state/parameter-context-listing/parameter-context-listing.effects.ts
Labels: hacktoberfest-accepted, new ui

#9336 [NIFI-13533] - Support dots in parameter names - parameter provider
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/parameter-providers/fetch-parameter-provider-parameters/fetch-parameter-provider-parameters.component.ts
Labels: hacktoberfest-accepted, new ui

#9325 NIFI-13820 autofocus Username field on Login Form
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/login/ui/login-form/login-form.component.html
Labels: new ui

#9337 NIFI-13823: Using startsWith testing content viewer compatibility to …
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/content-viewer/feature/content-viewer.component.ts
Labels: hacktoberfest-accepted, new ui

#9355 NIFI-13816: Ensuring the components in the Documentation are sorted.
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/documentation/feature/documentation.component.html
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/documentation/feature/documentation.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/process-group/edit-process-group/edit-process-group.component.html
Labels: hacktoberfest-accepted, new ui

#9343 [NIFI-13839] ensure contrast ratio for success, warn, error colors
  nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/src/app/pages/jolt-transform-json-ui/feature/jolt-transform-json-ui.component.html
  nifi-frontend/src/main/frontend/apps/nifi/src/app/_app.component-theme.scss
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/bulletins/ui/bulletin-board/bulletin-board-list/bulletin-board-list.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/documentation/feature/_documentation.component-theme.scss
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/manager/connection-manager.service.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/manager/port-manager.service.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/manager/process-group-manager.service.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/manager/processor-manager.service.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/manager/remote-process-group-manager.service.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/_canvas.component-theme.scss
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/canvas.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/header/flow-analysis-drawer/flow-analysis-drawer.component.html
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/header/flow-analysis-drawer/violation-details-dialog/_violation-details-dialog.component-theme.scss
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/header/flow-status/_flow-status.component-theme.scss
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/header/flow-status/flow-status.component.html
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/header/flow-status/flow-status.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/header/new-canvas-item/_new-canvas-item.component-theme.scss
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/common/breadcrumbs/breadcrumbs.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/parameter-contexts/ui/parameter-context-listing/edit-parameter-context/edit-parameter-context.component.html
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/provenance/feature/_provenance.component-theme.scss
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/provenance/ui/provenance-event-listing/provenance-event-table/lineage/_lineage.component-theme.scss
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/provenance/ui/provenance-event-listing/provenance-event-table/lineage/lineage.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/flow-analysis-rules/flow-analysis-rule-table/flow-analysis-rule-table.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/parameter-providers/fetch-parameter-provider-parameters/fetch-parameter-provider-parameters.component.html
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/settings/ui/reporting-tasks/reporting-task-table/reporting-task-table.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/summary/ui/common/cluster-summary-dialog/port-cluster-table/port-cluster-table.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/summary/ui/common/cluster-summary-dialog/processor-cluster-table/processor-cluster-table.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/summary/ui/common/cluster-summary-dialog/remote-process-group-cluster-table/remote-process-group-cluster-table.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/summary/ui/common/port-status-table/port-status-table.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/summary/ui/process-group-status-listing/process-group-status-table/process-group-status-table.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/summary/ui/processor-status-listing/processor-status-table/processor-status-table.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/summary/ui/remote-process-group-status-listing/remote-process-group-status-table/remote-process-group-status-table.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/context-menu/_context-menu.component-theme.scss
  nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/controller-service/controller-service-references/controller-service-references.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/controller-service/controller-service-table/controller-service-table.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/controller-service/disable-controller-service/disable-controller-service.component.html
  nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/controller-service/enable-controller-service/enable-controller-service.component.html
  nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/navigation/_navigation.component-theme.scss
  nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/parameter-references/parameter-references.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/property-verification/property-verification.component.html
  nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/status-history/_status-history.component-theme.scss
  nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/tooltips/property-hint-tip/_property-hint-tip.component-theme.scss
  nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_app.scss
  nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_codemirror-theme.scss
  nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_listing-table.scss
  nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_prism-theme.scss
  nifi-frontend/src/main/frontend/libs/shared/src/assets/themes/material.scss
  nifi-frontend/src/main/frontend/libs/shared/src/assets/themes/purple.scss
  nifi-frontend/src/main/frontend/libs/shared/src/components/resizable/_resizeable-theme.scss
Labels: hacktoberfest-accepted, new ui

#9342 [NIFI-13830] - Wait for canvas to complete loading before attempting to restore view or center
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.reducer.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/index.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/canvas.component.ts
Labels: hacktoberfest-accepted, new ui

#9366 [NIFI-13857] fix appearance and animations menu scrollbar issue
  nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_app.scss
Labels: hacktoberfest-accepted, new ui

#9374 [NIFI-13861] - Update to Nx 19.8.4 and Angular 18.2.8
  nifi-frontend/src/main/frontend/package-lock.json
  nifi-frontend/src/main/frontend/package.json
Labels: hacktoberfest-accepted, new ui

#9376 NIFI-13855: Ensuring that tooltips get closed when the host component…
  nifi-frontend/src/main/frontend/libs/shared/src/directives/nifi-tooltip.directive.ts
Labels: hacktoberfest-accepted, new ui

#9378 NIFI-13863: Fixing syntax highlighting for quoted parameters in prope…
  nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/property-table/editors/nf-editor/modes/nfel.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/property-table/editors/nf-editor/modes/nfpr.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/property-table/property-table.component.ts
Labels: hacktoberfest-accepted, new ui

#9377 NIFI-13849: Including parameter contexts in Convert to Parameter requ…
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/parameter-helper.service.ts
Labels: hacktoberfest-accepted, new ui

#9389 [NIFI-13780] fix jolt example input codemirror cursor issue
  nifi-frontend/src/main/frontend/apps/nifi-jolt-transform-ui/src/app/pages/jolt-transform-json-ui/feature/jolt-transform-json-ui.component.ts
Labels: hacktoberfest-accepted, new ui

#9370 [NIFI-13859] use tertiary color for spinners
  nifi-frontend/src/main/frontend/apps/nifi/src/app/app.component.html
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/login/feature/login.component.html
  nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_app.scss
Labels: hacktoberfest-accepted, new ui

#9391 NIFI-13873: Showing the spinner on the dialog buttons of Import From …
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.reducer.ts
Labels: hacktoberfest-accepted, new ui

#9408 [NIFI-12964] fix the alignment of the date picker icon
  nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_app.scss
Labels: hacktoberfest-accepted, new ui

#9406 [NIFI-13887] update styles of disabled drag/drop new canvas items
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/header/new-canvas-item/_new-canvas-item.component-theme.scss
  nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_app.scss
  nifi-frontend/src/main/frontend/libs/shared/src/assets/themes/material.scss
  nifi-frontend/src/main/frontend/libs/shared/src/assets/themes/purple.scss
Labels: hacktoberfest-accepted, new ui

#9428 [NIFI-13911] - force change detection after setting local variables i…
  nifi-frontend/src/main/frontend/apps/nifi/src/app/ui/common/property-table/property-table.component.ts
Labels: hacktoberfest-accepted, new ui

#9371 NIFI-13853: Added the ability to filter by all to the Advanced Rules page
  nifi-extension-bundles/nifi-update-attribute-bundle/nifi-update-attribute-ui/src/main/webapp/js/application.js
Labels: hacktoberfest-accepted

#9444 [NIFI-13925] update codemirror cursor and matching brackets
  nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_app.scss
  nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_codemirror-theme.scss
Labels: hacktoberfest-accepted, new ui

#9443 NIFI-13926: Removed used of default branch name in favor of null in I…
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/registry.service.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/import-from-registry/import-from-registry.component.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/items/flow/save-version-dialog/save-version-dialog.component.ts
Labels: hacktoberfest-accepted, new ui

#9435 NIFI-13921: Routing away from the edit path when closing the EditProc…
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
Labels: hacktoberfest-accepted, new ui

#9438 [NIFI-13920] fix draggable icon color while dragging
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/ui/canvas/header/new-canvas-item/_new-canvas-item.component-theme.scss
Labels: hacktoberfest-accepted, new ui

#9436 NIFI-13916: Removing width on action select in GlobalAccessPolicies.
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/access-policies/ui/global-access-policies/global-access-policies.component.scss
Labels: hacktoberfest-accepted, new ui

#9441 NIFI-249: Auto wrapping label text.
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/canvas-utils.service.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/canvas-view.service.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/service/manager/label-manager.service.ts
  nifi-frontend/src/main/frontend/apps/nifi/src/app/pages/flow-designer/state/transform/transform.selectors.ts
Labels: hacktoberfest-accepted, new ui

#9442 [NIFI-13917] update sidenav font color to match applicaiton font color
  nifi-frontend/src/main/frontend/libs/shared/src/assets/styles/_app.scss
Labels: hacktoberfest-accepted, new ui

#9464 NIFI-13943: Upgrade Dropbox, Salesforce, SNMP, and QuestDB depdendencies
  nifi-extension-bundles/nifi-dropbox-bundle/pom.xml
  nifi-extension-bundles/nifi-salesforce-bundle/nifi-salesforce-processors/pom.xml
  nifi-extension-bundles/nifi-snmp-bundle/nifi-snmp-processors/pom.xml
  nifi-extension-bundles/nifi-snmp-bundle/nifi-snmp-processors/src/main/java/org/apache/nifi/snmp/operations/SNMPTrapReceiverHandler.java
  nifi-extension-bundles/nifi-snmp-bundle/nifi-snmp-processors/src/main/java/org/apache/nifi/snmp/utils/SNMPUtils.java
  nifi-extension-bundles/nifi-snmp-bundle/nifi-snmp-processors/src/test/java/org/apache/nifi/snmp/factory/trap/V2TrapPDUFactoryTest.java
  nifi-framework-bundle/nifi-framework-extensions/nifi-questdb-bundle/nifi-questdb/pom.xml
Labels: hacktoberfest-accepted

#9465 NIFI-13944: Upgrade Redis to 5.2.0
  nifi-assembly/NOTICE
  nifi-extension-bundles/nifi-redis-bundle/nifi-redis-extensions/pom.xml
  nifi-extension-bundles/nifi-redis-bundle/nifi-redis-nar/src/main/resources/META-INF/LICENSE
  nifi-extension-bundles/nifi-redis-bundle/nifi-redis-nar/src/main/resources/META-INF/NOTICE
  nifi-extension-bundles/nifi-redis-bundle/nifi-redis-service-api-nar/src/main/resources/META-INF/NOTICE
  nifi-extension-bundles/nifi-redis-bundle/pom.xml
  pom.xml
Labels: hacktoberfest-accepted
